### PR TITLE
Init project

### PR DESCRIPTION
**Pull request by gdhaison**
===> Title: Init project, set up gems

===> Redmine ticket: https://edu-redmine.sun-asterisk.vn/issues/18944

===> Attachment files:

### CODE REVIEW

**Comment by gdhaison** [comment]
Screenshot from 2019-10-31 14-00-13

**Comment by gdhaison** [comment]
ready

**Comment by gdhaison** [comment]
ready

**Comment by gdhaison** [comment]
ready

**Comment by gdhaison** [comment]
ready

**Comment by gdhaison** [comment]
ready

**Comment by hungct-1121** [comment]
ready

**Pull request merged**
